###
GET http://localhost:3000

###
POST http://localhost:3000/servico/adicionar
Content-Type: application/json

{
    "nome": "D"
}

###
GET http://localhost:3000/servico/listar

###
DELETE http://localhost:3000/servico/deletar/6

###
GET http://localhost:3000/servico/buscar/4

###
GET http://localhost:3000/coordArea/listarRegistros/123456

###
GET http://localhost:3000/coordArea/verificaSituacao/345678

###
GET http://localhost:3000/coordArea/listarInstrutores/Tecnologia

###
PUT http://localhost:3000/coordArea/validarRegistro/10/4321
Content-Type: application/json

{
    
}


###
PUT http://localhost:3000/coordArea/validarParcialmenteRegistro/44/1234
Content-Type: application/json

{
    "justificativa": "Deu vontade",
    "total": "0"
}

###
POST http://localhost:3000/coordArea/registro/1234/789012
Content-Type: application/json

{
    "dataServico": "19-02-2024",
    "horaInicio": "10:00",
    "horaFinal": "13:00",
    "titulo": "Pabbabrte",
    "descricao": "Se coabayguso!!!",
    "FKservico": "2"
}