# Rota coordenador
###
GET http://localhost:3001/coordArea/listarRegistros/2345

###
GET http://localhost:3001/coordArea/1234

###
PUT http://localhost:3001/coordArea/validarRegistro/1234/4

###
PUT http://localhost:3001/coordArea/validarParcialmenteRegistro/1234/5
Content-Type: application/json

{
    "justificativa": "sousenac",
    "total": "00:00:00"
}

###
POST http://localhost:3001/coordArea/registro/1234/2345
Content-Type: application/json

{
    "dataServico": "2024-05-11",
    "horaInicio": "10:00:00",
    "horaFinal": "13:00:00",
    "titulo": "Pabbabrte",
    "descricao": "Se coabayguso!!!",
    "FKservico": "2"
}