# rotas de instrutor
###
GET  http://localhost:3001/instrutor/123456

###
GET  http://localhost:3001/instrutor/perfil/123456

###
POST http://localhost:3001/instrutor/registro/123456
Content-Type: application/json

{
    "dataServico": "2024-04-07",
    "horaInicio": "00:00",
    "horaFinal": "20:00",
    "titulo": "Workshop de",
    "descricao": "Workshop prático de técnicas de temperagem para a pascoa.",
    "FKservico": "1"
}

###
GET http://localhost:3001/instrutor/registros/123456

###
POST http://localhost:3001/instrutor/registros/123456
Content-Type: application/json

{
    "dataInicioFiltro": "",
    "dataFinalFiltro": "",
    "FKservico": ""
}

###
GET http://localhost:3001/instrutor/registro/123456/1

###
PUT http://localhost:3001/instrutor/registro/123456/1
Content-Type: application/json

{
    "dataServico": "2024-03-27",
    "horaInicio": "06:00:00",
    "horaFinal": "09:30:00",
    "titulo": "1º consulta com o zé boné",
    "descricao": "consulta de recomendação nutricional",
    "FKservico": "1"
}

###
DELETE http://localhost:3001/instrutor/registro/123456/7

###
GET http://localhost:3001/instrutor/servicos/123456
