# rotas de instrutor
###
GET  http://localhost:3001/instrutor/2345

###
GET  http://localhost:3001/instrutor/perfil/2345

###
POST http://localhost:3001/instrutor/registro/2345
Content-Type: application/json

{
    "dataServico": "2024-04-30",
    "horaInicio": "08:00:00",
    "horaFinal": "12:00:00",
    "titulo": "Material das aulas para turma de banco de dados",
    "descricao": "",
    "FKservico": "3"
}

###
GET http://localhost:3001/instrutor/registros/6789012345

###
POST http://localhost:3001/instrutor/registros/2345678901
Content-Type: application/json

{
    "dataInicioFiltro": "",
    "dataFinalFiltro": "",
    "FKservico": "1"
}

###
GET http://localhost:3001/instrutor/registro/2345678901/1

###
PUT http://localhost:3001/instrutor/registro/2345678901/1
Content-Type: application/json

{
    "dataServico": "2024-05-19",
    "horaInicio": "06:00:00",
    "horaFinal": "09:30:00",
    "titulo": "1º consulta com o zé boné",
    "descricao": "consulta de recomendação nutricional",
    "FKservico": "4"
}

###
DELETE http://localhost:3001/instrutor/registro/2345678901/2

###
GET http://localhost:3001/instrutor/servicos/2345678901
